on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

name: Checkout and Create Release Version

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      build: ${{ steps.check_release.outputs.build }}
    steps:
      - name: Get Version
        id: get_version
        run: |
            version=$(curl -s "https://api.github.com/repos/pyca/cryptography/tags" | jq -r '.[0].name')
            echo "version=${version}" >> $GITHUB_ENV
            echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Check Release
        id: check_release
        run: |
          if ! gh release view ${{ env.version }} -R ${{ github.repository }} | grep cryptography-.*.whl; then
            echo "build=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Tag
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a ${{ env.version }} -m "Release Version ${{ env.version }}" || echo "Tag already exists"
          git push origin ${{ env.version }} || echo "Tag already exists"

      - name: Create Release
        run: |
          gh release create ${{ env.version }} --notes "Release ${{ env.version }}" || echo "Release already exists"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: check
    runs-on: ${{ matrix.os }}
    if: ${{ needs.check.outputs.build == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y && yum install -y openssl-devel"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
    steps:
      - name: Get Version
        id: get_version
        run: |
            version=${{ needs.check.outputs.version }}
            echo "version=${version}" >> $GITHUB_ENV
            echo "Current Version: ${{ env.version }}"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: pyca/cryptography
          ref: ${{ env.version }}

      - name: Set up QEMU for multi-arch build
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x

      - name: Upload wheels
        run: |
          gh release upload ${{ env.version }} wheelhouse/*.whl -R ${{ github.repository }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}